name: hackerspace_game_jam_2023
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: 3.3.10

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flame: ^1.6.0
  flame_forge2d: ^0.12.5
  flame_tiled: ^1.9.1
  flame_audio: ^1.4.0
  flame_isolate: ^0.2.0
  bonfire: ^2.12.0
  image: ^4.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/player/
    - assets/images/enemy/
    - assets/images/npc/
    - assets/images/tile/
    - assets/images/tile_random/
    - assets/images/tiled/
    - assets/images/tiled/top_down/
    - assets/images/tiled/tileset/
    - assets/images/itens/
    - assets/images/lpc/body/
    - assets/images/lpc/feet/
    - assets/images/lpc/hair/
    - assets/images/lpc/leg/
    - assets/images/lpc/torco/
    - assets/images/lpc/head/
    - assets/images/lpc/gloves/